# Generated by Django 4.0.4 on 2023-09-04 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_detail', models.TextField()),
                ('status', models.CharField(choices=[('waiting_for_approval', 'Waiting for Approval'), ('approved', 'Approved'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='waiting_for_approval', max_length=20)),
            ],
            options={
                'ordering': ['-case_id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('Lawyer', 'Lawyer'), ('Client', 'Client')], max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='images/account.png', upload_to=mainapp.models.user.path_and_rename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_score', models.IntegerField()),
                ('review_detail', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_reviews', to='mainapp.customuser')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_reviews', to='mainapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('hiring_id', models.AutoField(primary_key=True, serialize=False)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_hirings', to='mainapp.customuser')),
                ('hired_lawyers', models.ManyToManyField(related_name='hired_lawyers', to='mainapp.customuser')),
            ],
            options={
                'ordering': ['-hire_date'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('detail', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.case')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('msg_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to='mainapp.customuser')),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to='mainapp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to='mainapp.customuser'),
        ),
        migrations.AddField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_cases', to='mainapp.customuser'),
        ),
    ]
